### ISSUE TITLE
Is this repository maintained? 

### ISSUE THREAD

**Issue by rufusshrestha** [florian/clipgerapp#1]
Is this repository maintained? This is the best highly efficient clipboard for macos but I can't find this in AppStore. Just concerned about any security issues.

**Comment by florian** [comment]
Hi. I didn't submit it to the Mac App Store because I would have to pay for a dev account and there are quite some hoops to jump through.

I haven't updated the code of this for a while either, but it's all open source so you can read it yourself and confirm that it's not doing something spooky :)

**Comment by rufusshrestha** [comment]
Thank you. Fair eough. It has exactly the feature I looked for (fuzzy search) and is a killer.

**Comment by florian** [comment]
Glad you like it! :)
